name: chat_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  flutter_svg: ^2.0.17
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  provider: ^6.1.2
  cloud_firestore: ^5.6.5
  flutter_dotenv: ^5.2.1
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/fonts/
    - assets/animations/
    - assets/images/

  fonts:
    - family: General Sans
      fonts:
        - asset: assets/fonts/GeneralSans/GeneralSans-Light.otf
          weight: 300
        - asset: assets/fonts/GeneralSans/GeneralSans-Regular.otf
          weight: 400
        - asset: assets/fonts/GeneralSans/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/fonts/GeneralSans/GeneralSans-Semibold.otf
          weight: 600
        - asset: assets/fonts/GeneralSans/GeneralSans-Bold.otf
          weight: 700

    - family: Clash Display
      fonts:
        - asset: assets/fonts/ClashDisplay/ClashDisplay-Light.otf
          weight: 300
        - asset: assets/fonts/ClashDisplay/ClashDisplay-Regular.otf
          weight: 400
        - asset: assets/fonts/ClashDisplay/ClashDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/ClashDisplay/ClashDisplay-Semibold.otf
          weight: 600
        - asset: assets/fonts/ClashDisplay/ClashDisplay-Bold.otf
          weight: 700
